tabs:
  fields:

    ####################################################
    # Tab: Info
    ####################################################

    website_lang:
      tab: Info
      label: Website Lang
      type: text
      comment: en, pt, pt-br, en-us
      default: en

    website_name:
      tab: Info
      label: Website Name
      type: text
      default: Homepage

    website_author:
      tab: Info
      label: Author
      type: text
      default: Jorge Rodrigues

    website_author_email:
      tab: Info
      label: Author Email
      type: text
      default: jorgerodrigues9@outlook.com

    website_url:
      tab: Info
      label: URL
      type: text
      default: "http://unscode.com"

    description:
      tab: Info
      label: Description
      type: textarea
      default: "Free Modern and Clean OctoberCMS Blog Theme."

    keywords:
      tab: Info
      label: Keywords
      type: taglist
      separator: comma
      default: october,octobercms,themes,templates,free octobercms themes, web developer,php,css,design,unscode
      options:
        - october
        - octobercms
        - themes
        - templates
        - free octobercms themes
        - web developer
        - php
        - css
        - design
        - unscode

    ####################################################
    # Tab: Assets
    ####################################################

    load_google_fonts:
      tab: Assets
      label: Google Fonts
      type: switch
      default: true

    google_font_family:
      tab: Assets
      label: Google Font Family
      type: text
      comment: Separate each font with vertical slash |
      default: "Roboto+Slab:300,400,700|Raleway:300,300i,400,400i,700,700i"
      trigger:
        action: show
        field: load_google_fonts
        condition: checked

    load_fontawesome:
      tab: Assets
      label: Font Awesome Icons (CDN)
      type: switch
      default: true

    load_jQuery:
      tab: Assets
      label: jQuery (CDN)
      type: switch
      default: true

    jQuery_version:
      tab: Assets
      label: jQuery Version
      type: dropdown
      default: 2.2.4
      options:
        3.3.1: 3.3.1
        2.2.4: 2.2.4
        1.12.4: 1.12.4
      trigger:
        action: show
        field: load_jQuery
        condition: checked

    ####################################################
    # Tab: Styles
    ####################################################

    primary_color:
      tab: Styles
      label: Primary Color
      type: colorpicker
      availableColors: ["#f44336","#9c27b0","#2196f3","#cddc39","#ffc107","#607d8b","#808080","#383838","#000000","#ffffff"]
      default: "#ff5722"
      assetVar: "primary-color"

    secondary_color:
      tab: Styles
      label: Secondary Color
      type: colorpicker
      availableColors: ["#f44336","#9c27b0","#2196f3","#cddc39","#ffc107","#607d8b","#808080","#383838","#000000","#ffffff"]
      default: "#2196f3"
      assetVar: "secondary-color"

    ####################################################
    # Tab: Addons
    ####################################################

    load_animate_css:
      tab: Addons
      label: Animate CSS
      type: switch
      default: true

    load_owl_carousel:
      tab: Addons
      label: Owl Carousel
      type: switch
      default: true

    ####################################################
    # Tab: Advanced
    ####################################################

    custom_css:
      tab: Advanced
      label: Custom CSS
      type: codeeditor
      size: huge
      language: css

    custom_js:
      tab: Advanced
      label: Custom JS
      type: codeeditor
      size: huge
      language: javascript
